FROM python:3.6

# Update the package lists
RUN apt-get update

COPY . /postgres_python

WORKDIR /postgres_python

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "postgres.py"]